version: "3.8"
services: 
  postgres_cadastro:
    container_name: postgres_cadastro_ifood
    image: postgres:12.3
    environment: 
      POSTGRES_USER: cadastro
      POSTGRES_PASSWORD: cadastro
      POSTGRES_DB: postgres
    ports: 
      - "5432:5432"
  keycloak_ifood:
    container_name: keycloak_ifood
    image: jboss/keycloak:11.0.0
    environment: 
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
    ports:
      - "8180:8080"